### ISSUE TITLE
Problem in interpolate!

### ISSUE THREAD

**Issue by ziyixi** [anowacki/SAC.jl#4]
The function `interpolate!` seems to have some bug in expression 
```s.b + (0:(npts-1))*delta```
 raising an error 
```MethodError: no method matching +(::Float32, ::StepRangeLen{Float32,Float64,Float64})```

And also it seems the test hasn't covered this function.

**Comment by ziyixi** [comment]
It could directly be fixed by:
```s.b .+ (0:(npts-1))*delta```

**Comment by anowacki** [comment]
Thanks for the report.  Which version of SAC.jl and Julia are you using?  ~~This error is not present on SAC.jl v0.3.0 with Julia v0.7 or v1.0, and~~ the broadcasting behaviour you show in `SAC.time` was changed in commit 1e38efc7.

**Comment by anowacki** [comment]
Apologies; the fix is only on a local commit which I'll push up soon.
